### ISSUE TITLE
Adding additional data sources

### ISSUE THREAD

**Issue by engn33r** [Zellic/Masamune#1]
Nice site, thanks for building :+1:

If you're adding past audit reports into your dataset, this is the best compilation of audit report links that I've seen https://github.com/0xNazgul/Blockchain-Security-Audit-List

In addition to audits and hacks, there's this list of bounty findings https://github.com/sirhashalot/SCV-List

And the readme says "Message me on Twitter" but your twitter dms appear disabled

**Comment by joswha** [comment]
Thanks! Updated the Twitter settings; I'll add the audits after I find a reasonable way to grep/ summarize the contents.

**Comment by engn33r** [comment]
I haven't looked at how it works and whether it could be integrated, but the jekyll just-the-docs template has a very fast search for the full content of the site, which might remove the need to summarize. Demonstrated at https://reports.yacademy.dev/

I noticed that there is a pause/freeze of the site when entering the first 2 characters, but I haven't seen this happen with the just-the-docs search. ippsec.rocks doesn't display results when there are too many matches, which may have been their fix to this.

**Comment by joswha** [comment]
Yep; there's a lot of findings that overlap in terms of their title/ description, so I figured allowing more results by default would be a better decision in terms of the relevancy of results. For now, I added a slight delay after the user stops writing, so that it has enough time to fetch the results. Should provide better UX.
